---
title: "visualisation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Visualisation

```{r vis1, echo=FALSE, eval=FALSE}
## load libraries
library(dplyr) # you need to have all libraries loaded within the Rmd file
library(ggplot2) #install.packages('ggplot2')
library(gapminder)

# get range of available data
summary(gapminder)

# setup dataframe
g = gapminder %>%
  filter(year==2007) %>%   # most recent year 
  mutate(pop_m = pop/1e6)  # population, millions

# plot scatterplot of most recent year 
s = ggplot(g, aes(x=gdpPercap, y=lifeExp)) +
  geom_point()
s

# add aesthetic of size by population
s = s + 
  aes(size=pop_m)
s

# add aesthetic of color by continent
s = s + 
  aes(color=continent)
s

# add title, update axes labels
s = s + 
  ggtitle('Health & Wealth of Nations for 2007') +
  xlab('GDP per capita ($/year)') +
  ylab('Life expectancy (years)')
s

# label legend
s = s + 
  scale_colour_discrete(name='Continent') +
  scale_size_continuous(name='Population (M)')
s

```

## Boxplots

```{r vis2, echo=FALSE, eval=FALSE}
g = gapminder %>%
  filter(year==2007) %>%   # most recent year 
  mutate(pop_m = pop/1e6)  # population, millions
  
  b = ggplot(g, aes(x=continent, y=lifeExp)) +
  geom_boxplot()
b

# match color to continents, like scatterplot
b = b +
  aes(fill=continent)
b

# drop legend, add title, update axes labels
b = b +
  theme(legend.position='none') +
  ggtitle('Life Expectancy by Continent for 2007') +
  xlab('Continent') +
  ylab('Life expectancy (years)')
b


```

```{r plotly, echo=FALSE}

library(dplyr) # you need to have all libraries loaded within the Rmd file
library(ggplot2) #install.packages('ggplot2')
library(gapminder)
library(plotly) # install.packages('plotly')
library(googleVis)

# setup dataframe
g = gapminder %>%
  filter(year==2007) %>%   # most recent year 
  mutate(pop_m = pop/1e6)  # population, millions

# scatterplot (Note: key=country shows up on rollover)
s = ggplot(g, aes(x=gdpPercap, y=lifeExp, key=country)) +
  geom_point()

s = s +
  aes(size=pop_m)

ggplotly(s) # must comment out or have eval=FALSE to knit

# boxplot
#ggplotly(b) # must comment out or have eval=FALSE to knit

```

## Including Plots

You can also embed plots, for example:

```{r cars, results='asis'}

op <- options(gvis.plot.tag='chart')

m = gvisMotionChart(
  gapminder %>%
    mutate(
      pop_m = pop / 1e6,
      log_gdpPercap = log(gdpPercap)), 
  idvar='country', 
  timevar='year', 
  xvar='log_gdpPercap', 
  yvar='lifeExp', 
  colorvar='continent',
  sizevar='pop_m')
plot(m)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
